### ISSUE TITLE
Echoic v2 roadmap

### ISSUE THREAD

**Issue by ipfans** [yeeuu/echoic#1]
Goals
---

- [ ] ```Context```, ```Request```, ```Response``` as interface.
- [ ] ```Middleware``` to interface.
- [ ] Wrapper method for old method.
